#logging.level.root: DEBUG

logging.level:
  org.springframework.web: ${LOG_LEVEL_SPRING_WEB:info}
  uk.gov.hmcts.reform.sscs: ${LOG_LEVEL_SSCS:info}
  uk.gov.hmcts.reform.sscs.idam.IdamApiClient: info
  uk.gov.hmcts.reform.ccd.client.CoreCaseDataApi: info
  uk.gov.hmcts.reform.ccd.document.EvidenceMetadataDownloadClientApi: info

feign:
  client:
    config:
      idam-api:
        loggerLevel: full
      core-case-data-api:
        loggerLevel: full
      document-management-metadata-download-api:
        loggerLevel: full

send-letter:
  url: ${SEND_LETTER_SERVICE_BASEURL:false}
  maxRetryAttempts: 3


amqp:
  password: ${AMQP_PASSWORD:guest}

