server:
  port: 8091

management:
  endpoints:
    web:
      base-path: /

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: sscs evidence share

amqp:
  host: ${AMQP_HOST:localhost}
  username: ${AMQP_USERNAME:guest}
  password: ${AMQP_PASSWORD:guest}
  topic: ${TOPIC_NAME:test.topic}
  subscription: ${SUBSCRIPTION_NAME:test.queue}
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: ${TRUST_ALL_CERTS:true}
