java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    PDF_SERVICE_BASE_URL: https://docmosis-development.platform.hmcts.net/rs/render
    PDF_SERVICE_HEALTH_URL: https://docmosis-development.platform.hmcts.net/rs/status
