java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    CORE_CASE_DATA_API_URL: "http://${SERVICE_NAME}-data-store-api"
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERVICE_ENABLED: "true"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-aat"
    TOPIC_NAME: "sscs-evidenceshare-topic-aat"
    AMQP_HOST: "sscs-servicebus-aat.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
    PDF_SERVICE_BASE_URL: ${PDF_SERVICE_BASE_URL}rs/render
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}
    PDF_SERVICE_HEALTH_URL: ${PDF_SERVICE_BASE_URL}rs/status
    IDAM_API_URL: ${IDAM_API_URL}
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    IDAM_S2S_AUTH: ${IDAM_S2S_AUTH}
    IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
    IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
    IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
    AMQP_PASSWORD: ${AMQP_PASSWORD}
    BUNDLE_STITCHING_ENABLED: "false"

tags:
  ccd-idam-pr: true

memoryRequests: "1024Mi"
cpuRequests: "25m"
memoryLimits: "4096Mi"
cpuLimits: "2500m"

ccd:
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      CCD Admin:
        - https://admin-web-${SERVICE_FQDN}/oauth2redirect

  apiGateway:
    s2sKey: ${API_GATEWAY_S2S_KEY}
    idamClientSecret:
      value: ${API_GATEWAY_IDAM_SECRET}

  userProfileApi:
    authorisedServices: ccd_admin,ccd_data,ccd_definition,sscs

  dataStoreApi:
    s2sKey: ${DATA_STORE_S2S_KEY}
    s2sAuthorisedServices: sscs,ccd_gw

  definitionStoreApi:
    s2sKey: ${DEFINITION_STORE_S2S_KEY}
    s2sAuthorisedServices: ccd_admin,ccd_data,sscs,ccd_gw

  caseManagementWeb:
    enabled: true # if you need access to the web ui then enable this, otherwise it won't be deployed
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  adminWeb:
    enabled: false # if you need access to the admin web ui then enable this, otherwise it won't be deployed
    s2sKey: ${ADMIN_S2S_KEY}
    idamClientSecret:
      value: ${ADMIN_WEB_IDAM_SECRET}
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - SSCS
      users:
        - system.update@hmcts.net|SSCS|Benefit|appealCreated
      userProfileDatabaseHost: ${SERVICE_NAME}-ccd-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: hmcts
      userProfileDatabasePassword: hmcts
      userProfileDatabaseName: user-profile
    definition:
      enabled: true
      image: hmctspublic.azurecr.io/sscs/ccd-definition-importer-benefit:5.1.21
      kvSecretRef: kvcreds
      gitSecretRef: kvcreds
      redirectUri: https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      definitionFilename: sscs-ccd.xlsx
      userRoles:
        - citizen
        - caseworker
        - caseworker-sscs
        - caseworker-sscs-systemupdate
        - caseworker-sscs-anonymouscitizen
        - caseworker-sscs-callagent
        - caseworker-sscs-judge
        - caseworker-sscs-clerk
        - caseworker-sscs-dwpresponsewriter
        - caseworker-sscs-registrar
        - caseworker-sscs-superuser
        - caseworker-sscs-teamleader
        - caseworker-sscs-panelmember
        - caseworker-sscs-bulkscan
