java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  environment:
    SEND_LETTER_SERVICE_ENABLED: "true"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-aat"
    TOPIC_NAME: "sscs-evidenceshare-topic-aat"
    AMQP_HOST: "sscs-servicebus-aat.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
    PDF_SERVICE_BASE_URL: ${PDF_SERVICE_BASE_URL}rs/render
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}
    PDF_SERVICE_HEALTH_URL: ${PDF_SERVICE_BASE_URL}rs/status
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    IDAM_S2S_AUTH: ${IDAM_S2S_AUTH}
    IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
    BUNDLE_STITCHING_ENABLED: "false"
    READY_TO_LIST_ROBOTICS_ENABLED: "false"
