java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 8091
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - idam-api
        - idam-oauth-user
        - idam-redirect
        - idam-sscs-systemupdate-user
        - idam-sscs-systemupdate-password
        - idam-sscs-oauth2-client-secret
        - ccd-api
        - ccd-jid
        - ccd-tid
        - idam-s2s-api
        - sscs-s2s-secret
        - s2s-micro
        - sscs-asb-primary-send-and-listen-shared-access-key
    docmosisiaasdevkv:
      resourceGroup: docmosisiaasdevkv
      secrets:
        - docmosis-endpoint
        - docmosis-api-key
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-tribunals-api
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_API_URL: ${IDAM_API_URL}
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    IDAM_S2S_AUTH: ${IDAM_S2S_AUTH}
    IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
    IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
    IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    CORE_CASE_DATA_JURISDICTION_ID: SSCS
    CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERVICE_ENABLED: "true"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    TRUST_ALL_CERTS: "true"
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-aat"
    TOPIC_NAME: "sscs-evidenceshare-topic-aat"
    AMQP_HOST: "sscs-servicebus-aat.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
    AMQP_PASSWORD: ${AMQP_PASSWORD}
    PDF_SERVICE_BASE_URL: ${PDF_SERVICE_BASE_URL}rs/render
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}
    PDF_SERVICE_HEALTH_URL: ${PDF_SERVICE_BASE_URL}rs/status
