java:
  image: 'https://hmcts.azurecr.io/hmcts/sscs-evidence-share:latest'
  applicationPort: 8091
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - idam-api
        - idam-oauth-user
        - idam-redirect
        - idam-sscs-systemupdate-user
        - idam-sscs-systemupdate-password
        - idam-sscs-oauth2-client-secret
        - ccd-api
        - ccd-jid
        - ccd-tid
        - idam-s2s-api
        - sscs-s2s-secret
        - s2s-micro
        - sscs-asb-primary-send-and-listen-shared-access-key
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-evidence-share
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    CORE_CASE_DATA_JURISDICTION_ID: SSCS
    CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERVICE_ENABLED: "true"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    TRUST_ALL_CERTS: "true"
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-aat"
    TOPIC_NAME: "sscs-evidenceshare-topic-aat"
    AMQP_HOST: "sscs-servicebus-aat.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
