apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - image: ${IMAGE_NAME}
          name: ${SERVICE_NAME}
          ports:
            - containerPort: 8080
          env:
            - name: IDAM_API_URL
              value: ${IDAM_API_URL}
            - name: CORE_CASE_DATA_API_URL
              value: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
            - name: IDAM.S2S-AUTH.TOTP_SECRET
              value: ${IDAM_S2S_AUTH_TOTP_SECRET}
            - name: IDAM.S2S-AUTH
              value: ${IDAM_S2S_AUTH}
            - name: IDAM.S2S-AUTH.MICROSERVICE
              value: ${IDAM_S2S_AUTH_MICROSERVICE}
            - name: IDAM_SSCS_SYSTEMUPDATE_USER
              value: ${IDAM_SSCS_SYSTEMUPDATE_USER}
            - name: IDAM_SSCS_SYSTEMUPDATE_PASSWORD
              value: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
            - name: IDAM_OAUTH2_CLIENT_ID
              value: "sscs"
            - name: IDAM_OAUTH2_CLIENT_SECRET
              value: ${IDAM_OAUTH2_CLIENT_SECRET}
            - name: IDAM_OAUTH2_REDIRECT_URL
              value: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
            - name: DOCUMENT_MANAGEMENT_URL
              value: "http://dm-store-aat.service.core-compute-aat.internal"
            - name: SEND_LETTER_SERVICE_BASEURL
              value: "http://rpe-send-letter-service-${var.env}.service.core-compute-aat.internal"
            - name: SEND_LETTER_SERVICE_ENABLED
              value: true
            - name: DOCUMENT_MANAGEMENT_URL
              value: "http://dm-store-aat.service.core-compute.internal"
            - name: TRUST_ALL_CERTS
              value: true
            - name: SUBSCRIPTION_NAME
              value: "evidenceshare-subscription"
            - name: TOPIC_NAME
              value: "evidenceshare-topic"
            - name: AMQP_HOST
              value: "sscs-servicebus-aat.servicebus.windows.net"
            - name: AMQP_USERNAME
              value: "SendAndListenSharedAccessKey"
            - name: AMQP_PASSWORD
              value: ${AMQP_PASSWORD}
            - name: PDF_SERVICE_BASE_URL:
              value:
            - name: PDF_SERVICE_ACCESS_KEY:
              value:
            - name: PDF_SERVICE_HEALTH_UR:
              value:



          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "2500m"

          readinessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: ${SERVICE_NAME}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: ${SERVICE_FQDN}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${SERVICE_NAME}
              servicePort: 80
